# Generated by Django 5.1.5 on 2026-04-30 10:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_enrollment_enrollment_unique_student_class_when_no_course'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassWeeklyStats',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start_date', models.DateField()),
                ('avg_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('at_risk_count', models.PositiveSmallIntegerField(default=0)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_stats', to='academics.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
            ],
            options={
                'ordering': ['-week_start_date'],
                'abstract': False,
                'indexes': [models.Index(fields=['school', 'created_at'], name='analytics_cls_school_cat_idx'), models.Index(fields=['school', 'klass', 'week_start_date'], name='anlyt_cls_klass_week_idx')],
                'constraints': [models.UniqueConstraint(fields=('klass', 'week_start_date'), name='class_weekly_stats_unique_per_week')],
            },
        ),
        migrations.CreateModel(
            name='RiskSignal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('kind', models.CharField(choices=[('ATTENDANCE', 'Attendance'), ('ACADEMIC', 'Academic'), ('BEHAVIOR', 'Behavior')], max_length=15)),
                ('reason', models.TextField()),
                ('evidence_json', models.JSONField(default=dict)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_risks', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['school', 'created_at'], name='analytics_risk_school_cat_idx'), models.Index(fields=['school', 'student', 'level'], name='analytics_risk_stud_level_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentDailyStats',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quizzes_taken', models.PositiveSmallIntegerField(default=0)),
                ('avg_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
                'indexes': [models.Index(fields=['school', 'created_at'], name='analytics_stu_school_cat_idx'), models.Index(fields=['school', 'student', 'date'], name='anlyt_stu_stud_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='student_daily_stats_unique_per_day')],
            },
        ),
    ]
