# Generated by Django 5.1.5 on 2026-04-30 10:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_enrollment_enrollment_unique_student_class_when_no_course'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('VIDEO', 'Video'), ('PDF', 'PDF'), ('ARTICLE', 'Article'), ('INTERACTIVE', 'Interactive'), ('COURSE', 'Course')], max_length=15)),
                ('file_url', models.URLField(max_length=500)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('ai_tags', models.JSONField(default=list)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='academics.course')),
                ('klass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='academics.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['school', 'created_at'], name='content_item_school_cat_idx'), models.Index(fields=['school', 'course', 'kind'], name='cnt_item_course_kind_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('VIDEO', 'Video'), ('PDF', 'PDF'), ('ARTICLE', 'Article'), ('INTERACTIVE', 'Interactive'), ('COURSE', 'Course')], max_length=15)),
                ('price_inr', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('file_url', models.URLField(max_length=500)),
                ('cover_image_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('author_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'featured'], name='mktpl_active_featured_idx'), models.Index(fields=['kind', 'is_active'], name='marketplace_kind_active_idx')],
            },
        ),
    ]
