# Generated by Django 5.1.5 on 2026-04-23 05:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. 2025-26', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False, help_text='At most one is_current=True per school is enforced at save time.')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
            ],
            options={
                'ordering': ['-start_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.PositiveSmallIntegerField()),
                ('section', models.CharField(max_length=4)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academics.academicyear')),
                ('class_teacher', models.ForeignKey(blank=True, help_text='Optional. Must be a TEACHER in the same school.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_as_teacher', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'ordering': ['grade', 'section'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(help_text='e.g. MATH-10, AI-INTRO', max_length=30)),
                ('stream', models.CharField(choices=[('AI', 'AI'), ('CODE', 'Coding'), ('ROBOT', 'Robotics'), ('STEM', 'STEM'), ('GENERAL', 'General')], default='GENERAL', max_length=10)),
                ('grade_min', models.PositiveSmallIntegerField(default=1)),
                ('grade_max', models.PositiveSmallIntegerField(default=12)),
                ('description', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolled_on', models.DateField(auto_now_add=True)),
                ('withdrawn_on', models.DateField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.course')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_on'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['school', 'created_at'], name='academics_a_school__eae5e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='academic_year_unique_name_per_school'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['school', 'created_at'], name='academics_c_school__dfb426_idx'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'grade', 'section'), name='class_unique_grade_section_per_year'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.CheckConstraint(condition=models.Q(('grade__gte', 1), ('grade__lte', 12)), name='class_grade_in_range'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['school', 'created_at'], name='academics_c_school__192bbd_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='course_unique_code_per_school'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('grade_min__lte', models.F('grade_max'))), name='course_grade_range_valid'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['school', 'created_at'], name='academics_e_school__8b18b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'klass', 'course'), name='enrollment_unique_student_class_course'),
        ),
    ]
