# Generated by Django 5.1.5 on 2026-04-25 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', True)), fields=('student', 'klass'), name='enrollment_unique_student_class_when_no_course'),
        ),
    ]
